/* Product and category data. Replace placeholder entries (brand "Sample brand")
   and fill in null fields (rating, desc, bestFor) before launch. */
var STORE_CATEGORIES = [
 {
  "slug": "laptops",
  "title": "Gaming laptops",
  "intro": "Gaming laptops from leading brands, with GPU, display and memory options at each price point."
 },
 {
  "slug": "monitors",
  "title": "Gaming monitors",
  "intro": "Refresh rate, panel type and adaptive sync for competitive and cinematic play."
 },
 {
  "slug": "televisions",
  "title": "Televisions",
  "intro": "OLED and QLED televisions with 120Hz panels and HDMI 2.1 for current consoles."
 },
 {
  "slug": "smartphones",
  "title": "Gaming smartphones",
  "intro": "Phones built for sustained play, with high refresh displays, cooling and physical gaming controls."
 },
 {
  "slug": "graphics-cards",
  "title": "Graphics cards",
  "intro": "NVIDIA and AMD desktop graphics cards for gaming, streaming and rendering."
 },
 {
  "slug": "mouse",
  "title": "Mouse",
  "intro": "Sample listings until real mouse products are added."
 },
 {
  "slug": "keyboards",
  "title": "Keyboards",
  "intro": "Sample listings until real keyboard products are added."
 },
 {
  "slug": "tablets",
  "title": "Tablets",
  "intro": "Sample listings until real tablet products are added."
 },
 {
  "slug": "accessories",
  "title": "Accessories",
  "intro": "Sample listings for chargers, power banks and cables until real products are added."
 }
];
var STORE_PRODUCTS = [
 {
  "id": "lap-001",
  "cat": "laptops",
  "brand": "ASUS ROG",
  "name": "ROG Strix G16",
  "spec": "16-inch QHD 240Hz, RTX 4070, 16GB RAM",
  "price": 149990,
  "was": 164990,
  "stock": "In stock",
  "img": "images/rog-strix-g16.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "asus-rog-rog-strix-g16",
  "url": "products/asus-rog-rog-strix-g16.html",
  "w": 640,
  "h": 640
 },
 {
  "id": "lap-002",
  "cat": "laptops",
  "brand": "Lenovo Legion",
  "name": "Legion Pro 5i",
  "spec": "Core i7-14650HX, RTX 5060, 16-inch",
  "price": 139990,
  "was": null,
  "stock": "Few left",
  "img": "images/legion-pro-5i.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "lenovo-legion-legion-pro-5i",
  "url": "products/lenovo-legion-legion-pro-5i.html",
  "w": 640,
  "h": 640
 },
 {
  "id": "lap-003",
  "cat": "laptops",
  "brand": "MSI",
  "name": "Katana 15",
  "spec": "15.6-inch 165Hz, RTX 5050",
  "price": 96990,
  "was": 104990,
  "stock": "In stock",
  "img": "images/katana-15.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "msi-katana-15",
  "url": "products/msi-katana-15.html",
  "w": 300,
  "h": 187
 },
 {
  "id": "lap-004",
  "cat": "laptops",
  "brand": "Acer Predator",
  "name": "Helios Neo 16",
  "spec": "16-inch QHD 165Hz, RTX 4060, 16GB RAM",
  "price": 98990,
  "was": null,
  "stock": "In stock",
  "img": "images/helios-neo-16.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "acer-predator-helios-neo-16",
  "url": "products/acer-predator-helios-neo-16.html",
  "w": 300,
  "h": 188
 },
 {
  "id": "lap-005",
  "cat": "laptops",
  "brand": "Alienware",
  "name": "m16 R2",
  "spec": "16-inch QHD+ 240Hz, RTX 4070, 16GB RAM",
  "price": 169990,
  "was": 179990,
  "stock": "Few left",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "alienware-m16-r2",
  "url": "products/alienware-m16-r2.html",
  "w": null,
  "h": null
 },
 {
  "id": "lap-006",
  "cat": "laptops",
  "brand": "HP Omen",
  "name": "Omen 16",
  "spec": "16-inch QHD 165Hz, RTX 4060, 16GB RAM",
  "price": 112990,
  "was": 121990,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "hp-omen-omen-16",
  "url": "products/hp-omen-omen-16.html",
  "w": null,
  "h": null
 },
 {
  "id": "mon-001",
  "cat": "monitors",
  "brand": "ASUS ROG",
  "name": "Swift PG27AQN",
  "spec": "27-inch QHD 360Hz, IPS panel",
  "price": 74990,
  "was": 84990,
  "stock": "In stock",
  "img": "images/swift-pg27aqn.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "asus-rog-swift-pg27aqn",
  "url": "products/asus-rog-swift-pg27aqn.html",
  "w": 640,
  "h": 471
 },
 {
  "id": "mon-002",
  "cat": "monitors",
  "brand": "Samsung Odyssey",
  "name": "G5 G50D",
  "spec": "27-inch QHD 165Hz, 1ms, FreeSync",
  "price": 16990,
  "was": 21990,
  "stock": "In stock",
  "img": "images/g5-g50d.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "samsung-odyssey-g5-g50d",
  "url": "products/samsung-odyssey-g5-g50d.html",
  "w": 640,
  "h": 640
 },
 {
  "id": "mon-003",
  "cat": "monitors",
  "brand": "LG UltraGear",
  "name": "27GP850",
  "spec": "27-inch QHD 200Hz, FreeSync and G-Sync",
  "price": 21990,
  "was": null,
  "stock": "Few left",
  "img": "images/27gp850.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "lg-ultragear-27gp850",
  "url": "products/lg-ultragear-27gp850.html",
  "w": 300,
  "h": 300
 },
 {
  "id": "mon-004",
  "cat": "monitors",
  "brand": "MSI",
  "name": "MAG 274QRF",
  "spec": "27-inch QHD 240Hz, Rapid IPS",
  "price": 18990,
  "was": 22990,
  "stock": "In stock",
  "img": "images/mag-274qrf.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "msi-mag-274qrf",
  "url": "products/msi-mag-274qrf.html",
  "w": 640,
  "h": 639
 },
 {
  "id": "tv-001",
  "cat": "televisions",
  "brand": "LG",
  "name": "C4 OLED 55-inch",
  "spec": "4K OLED, 120Hz, HDMI 2.1, Game Optimiser",
  "price": 124990,
  "was": 149990,
  "stock": "In stock",
  "img": "images/c4-oled-55-inch.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "lg-c4-oled-55-inch",
  "url": "products/lg-c4-oled-55-inch.html",
  "w": 447,
  "h": 447
 },
 {
  "id": "tv-002",
  "cat": "televisions",
  "brand": "Samsung",
  "name": "S90D OLED 55-inch",
  "spec": "4K QD-OLED, 144Hz, HDMI 2.1",
  "price": 139990,
  "was": null,
  "stock": "In stock",
  "img": "images/s90d-oled-55-inch.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "samsung-s90d-oled-55-inch",
  "url": "products/samsung-s90d-oled-55-inch.html",
  "w": 447,
  "h": 447
 },
 {
  "id": "tv-003",
  "cat": "televisions",
  "brand": "Sony",
  "name": "Bravia 8 55-inch",
  "spec": "55-inch 4K XR OLED, Google TV, Dolby Vision",
  "price": 169990,
  "was": 184990,
  "stock": "Few left",
  "img": "images/bravia-8-55-inch.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "sony-bravia-8-55-inch",
  "url": "products/sony-bravia-8-55-inch.html",
  "w": 640,
  "h": 640
 },
 {
  "id": "tv-004",
  "cat": "televisions",
  "brand": "TCL",
  "name": "QM8K 65-inch",
  "spec": "4K QLED Mini LED, 144Hz, HDMI 2.1",
  "price": 99990,
  "was": 119990,
  "stock": "In stock",
  "img": "images/qm8k-65-inch.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "tcl-qm8k-65-inch",
  "url": "products/tcl-qm8k-65-inch.html",
  "w": 225,
  "h": 225
 },
 {
  "id": "ph-001",
  "cat": "smartphones",
  "brand": "ASUS ROG",
  "name": "ROG Phone 9",
  "spec": "6.78-inch 165Hz AMOLED, 24GB RAM, AirTriggers",
  "price": 74999,
  "was": 84999,
  "stock": "In stock",
  "img": "images/rog-phone-9.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "asus-rog-rog-phone-9",
  "url": "products/asus-rog-rog-phone-9.html",
  "w": 225,
  "h": 225
 },
 {
  "id": "ph-002",
  "cat": "smartphones",
  "brand": "Nubia RedMagic",
  "name": "RedMagic 9 Pro",
  "spec": "6.8-inch 144Hz AMOLED, active cooling fan",
  "price": 56999,
  "was": 64999,
  "stock": "In stock",
  "img": "images/redmagic-9-pro.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "nubia-redmagic-redmagic-9-pro",
  "url": "products/nubia-redmagic-redmagic-9-pro.html",
  "w": 493,
  "h": 622
 },
 {
  "id": "ph-003",
  "cat": "smartphones",
  "brand": "Lenovo Legion",
  "name": "Legion Y70",
  "spec": "6.67-inch 144Hz AMOLED, 16GB RAM",
  "price": 49999,
  "was": null,
  "stock": "Few left",
  "img": "images/legion-y70.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "lenovo-legion-legion-y70",
  "url": "products/lenovo-legion-legion-y70.html",
  "w": 554,
  "h": 554
 },
 {
  "id": "gpu-001",
  "cat": "graphics-cards",
  "brand": "NVIDIA GeForce",
  "name": "RTX 4070",
  "spec": "12GB GDDR6X, DLSS 3, ray tracing",
  "price": 58990,
  "was": 62990,
  "stock": "In stock",
  "img": "images/rtx-4070.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "nvidia-geforce-rtx-4070",
  "url": "products/nvidia-geforce-rtx-4070.html",
  "w": 640,
  "h": 640
 },
 {
  "id": "gpu-002",
  "cat": "graphics-cards",
  "brand": "NVIDIA GeForce",
  "name": "RTX 4060 Ti",
  "spec": "8GB or 16GB GDDR6, DLSS 3",
  "price": 42990,
  "was": null,
  "stock": "In stock",
  "img": "images/rtx-4060-ti.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "nvidia-geforce-rtx-4060-ti",
  "url": "products/nvidia-geforce-rtx-4060-ti.html",
  "w": 600,
  "h": 600
 },
 {
  "id": "gpu-003",
  "cat": "graphics-cards",
  "brand": "AMD Radeon",
  "name": "RX 7800 XT",
  "spec": "16GB GDDR6, FSR 3",
  "price": 49990,
  "was": 54990,
  "stock": "Few left",
  "img": "images/rx-7800-xt.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "amd-radeon-rx-7800-xt",
  "url": "products/amd-radeon-rx-7800-xt.html",
  "w": 453,
  "h": 441
 },
 {
  "id": "gpu-004",
  "cat": "graphics-cards",
  "brand": "Intel Arc",
  "name": "Arc B580",
  "spec": "12GB GDDR6, XeSS, AV1 encoding",
  "price": 24990,
  "was": null,
  "stock": "In stock",
  "img": "images/arc-b580.webp",
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": false,
  "slug": "intel-arc-arc-b580",
  "url": "products/intel-arc-arc-b580.html",
  "w": 640,
  "h": 640
 },
 {
  "id": "ms-001",
  "cat": "mouse",
  "brand": "Sample brand",
  "name": "Sample mouse 1",
  "spec": "Not provided",
  "price": 1999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-mouse-1",
  "url": "products/sample-brand-sample-mouse-1.html",
  "w": null,
  "h": null
 },
 {
  "id": "ms-002",
  "cat": "mouse",
  "brand": "Sample brand",
  "name": "Sample mouse 2",
  "spec": "Not provided",
  "price": 2499,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-mouse-2",
  "url": "products/sample-brand-sample-mouse-2.html",
  "w": null,
  "h": null
 },
 {
  "id": "ms-003",
  "cat": "mouse",
  "brand": "Sample brand",
  "name": "Sample mouse 3",
  "spec": "Not provided",
  "price": 2999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-mouse-3",
  "url": "products/sample-brand-sample-mouse-3.html",
  "w": null,
  "h": null
 },
 {
  "id": "kb-001",
  "cat": "keyboards",
  "brand": "Sample brand",
  "name": "Sample keyboard 1",
  "spec": "Not provided",
  "price": 2999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-keyboard-1",
  "url": "products/sample-brand-sample-keyboard-1.html",
  "w": null,
  "h": null
 },
 {
  "id": "kb-002",
  "cat": "keyboards",
  "brand": "Sample brand",
  "name": "Sample keyboard 2",
  "spec": "Not provided",
  "price": 3499,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-keyboard-2",
  "url": "products/sample-brand-sample-keyboard-2.html",
  "w": null,
  "h": null
 },
 {
  "id": "kb-003",
  "cat": "keyboards",
  "brand": "Sample brand",
  "name": "Sample keyboard 3",
  "spec": "Not provided",
  "price": 4499,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-keyboard-3",
  "url": "products/sample-brand-sample-keyboard-3.html",
  "w": null,
  "h": null
 },
 {
  "id": "tab-001",
  "cat": "tablets",
  "brand": "Sample brand",
  "name": "Sample tablet 1",
  "spec": "Not provided",
  "price": 14999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-tablet-1",
  "url": "products/sample-brand-sample-tablet-1.html",
  "w": null,
  "h": null
 },
 {
  "id": "tab-002",
  "cat": "tablets",
  "brand": "Sample brand",
  "name": "Sample tablet 2",
  "spec": "Not provided",
  "price": 19999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-tablet-2",
  "url": "products/sample-brand-sample-tablet-2.html",
  "w": null,
  "h": null
 },
 {
  "id": "tab-003",
  "cat": "tablets",
  "brand": "Sample brand",
  "name": "Sample tablet 3",
  "spec": "Not provided",
  "price": 24999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-tablet-3",
  "url": "products/sample-brand-sample-tablet-3.html",
  "w": null,
  "h": null
 },
 {
  "id": "acc-001",
  "cat": "accessories",
  "brand": "Sample brand",
  "name": "Sample accessory 1",
  "spec": "Not provided",
  "price": 1499,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-accessory-1",
  "url": "products/sample-brand-sample-accessory-1.html",
  "w": null,
  "h": null
 },
 {
  "id": "acc-002",
  "cat": "accessories",
  "brand": "Sample brand",
  "name": "Sample accessory 2",
  "spec": "Not provided",
  "price": 1999,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-accessory-2",
  "url": "products/sample-brand-sample-accessory-2.html",
  "w": null,
  "h": null
 },
 {
  "id": "acc-003",
  "cat": "accessories",
  "brand": "Sample brand",
  "name": "Sample accessory 3",
  "spec": "Not provided",
  "price": 2499,
  "was": null,
  "stock": "In stock",
  "img": null,
  "rating": null,
  "desc": null,
  "bestFor": null,
  "placeholder": true,
  "slug": "sample-brand-sample-accessory-3",
  "url": "products/sample-brand-sample-accessory-3.html",
  "w": null,
  "h": null
 }
];
